# config/config.yml
development:
  rtorret_scgi: http://SOKAR/RPC2
  download_directory: /Volumes/incoming/

test:
  rtorret_scgi: http://SOKAR/RPC2
  download_directory: /Volumes/incoming/

production:
  rtorret_scgi: http://SOKAR/RPC2
  download_directory: /Volumes/incoming/
